import 'package:remixicon/remixicon.dart';
import 'package:qr_app/controller/my_controller.dart';

class RemixIconController extends MyController {
  List iconsData = [
    {
      "icon": RemixIcons.arrow_left_up_box_line,
      "name": "arrow_left_up_box_line",
    },
    {
      "icon": RemixIcons.arrow_right_up_box_line,
      "name": "arrow_right_up_box_line",
    },
    {
      "icon": RemixIcons.arrow_left_down_box_line,
      "name": "arrow_left_down_box_line",
    },
    {
      "icon": RemixIcons.arrow_right_down_box_line,
      "name": "arrow_right_down_box_line",
    },
    {"icon": RemixIcons.arrow_left_box_line, "name": "arrow_left_box_line"},
    {"icon": RemixIcons.arrow_right_box_line, "name": "arrow_right_box_line"},
    {"icon": RemixIcons.arrow_up_box_line, "name": "arrow_up_box_line"},
    {"icon": RemixIcons.arrow_down_box_line, "name": "arrow_down_box_line"},
    {"icon": RemixIcons.arrow_left_line, "name": "arrow_left_line"},
    {"icon": RemixIcons.arrow_right_line, "name": "arrow_right_line"},
    {"icon": RemixIcons.arrow_up_line, "name": "arrow_up_line"},
    {"icon": RemixIcons.arrow_down_line, "name": "arrow_down_line"},
    {"icon": RemixIcons.arrow_left_up_line, "name": "arrow_left_up_line"},
    {"icon": RemixIcons.arrow_right_up_line, "name": "arrow_right_up_line"},
    {"icon": RemixIcons.arrow_left_down_line, "name": "arrow_left_down_line"},
    {"icon": RemixIcons.arrow_right_down_line, "name": "arrow_right_down_line"},
    {"icon": RemixIcons.arrow_right_down_line, "name": "arrow_right_down_line"},
    {"icon": RemixIcons.alert_fill, "name": "alert_fill"},
    {"icon": RemixIcons.account_box_fill, "name": "account_box_fill"},
    {"icon": RemixIcons.add_box_fill, "name": "add_box_fill"},
    {"icon": RemixIcons.arrow_up_circle_fill, "name": "arrow_up_circle_fill"},
    {"icon": RemixIcons.arrow_up_fill, "name": "arrow_up_fill"},
    {"icon": RemixIcons.arrow_down_fill, "name": "arrow_down_fill"},
    {"icon": RemixIcons.arrow_right_fill, "name": "arrow_right_fill"},
    {"icon": RemixIcons.arrow_left_fill, "name": "arrow_left_fill"},
    {"icon": RemixIcons.home_fill, "name": "home_fill"},
    {"icon": RemixIcons.home_office_fill, "name": "home_office_fill"},
    {"icon": RemixIcons.building_fill, "name": "building_fill"},
    {"icon": RemixIcons.store_fill, "name": "store_fill"},
    {"icon": RemixIcons.bank_fill, "name": "bank_fill"},
    {"icon": RemixIcons.hospital_fill, "name": "hospital_fill"},
    {"icon": RemixIcons.tent_fill, "name": "tent_fill"},
    {"icon": RemixIcons.school_fill, "name": "school_fill"},
    {"icon": RemixIcons.government_fill, "name": "government_fill"},
    {"icon": RemixIcons.tent_fill, "name": "tent_fill"},
    {"icon": RemixIcons.mail_fill, "name": "mail_fill"},
    {"icon": RemixIcons.mail_unread_fill, "name": "mail_unread_fill"},
    {"icon": RemixIcons.mail_add_fill, "name": "mail_add_fill"},
    {"icon": RemixIcons.mail_check_fill, "name": "mail_check_fill"},
    {"icon": RemixIcons.mail_close_fill, "name": "mail_close_fill"},
    {"icon": RemixIcons.mail_download_fill, "name": "mail_download_fill"},
    {"icon": RemixIcons.mail_forbid_fill, "name": "mail_forbid_fill"},
    {"icon": RemixIcons.mail_lock_fill, "name": "mail_lock_fill"},
    {"icon": RemixIcons.mail_settings_fill, "name": "mail_settings_fill"},
    {"icon": RemixIcons.mail_star_fill, "name": "mail_star_fill"},
    {"icon": RemixIcons.mail_volume_fill, "name": "mail_volume_fill"},
    {"icon": RemixIcons.inbox_fill, "name": "inbox_fill"},
    {"icon": RemixIcons.inbox_archive_fill, "name": "inbox_archive_fill"},
    {"icon": RemixIcons.inbox_unarchive_fill, "name": "inbox_unarchive_fill"},
  ];
}
